// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class ArizaTuru
    {
        [Key]
        public int ArizaTuruId { get; set; }
        [StringLength(10)]
        public string ArizaTuruAdi { get; set; }
        public int EkipmanTurId { get; set; }

        [ForeignKey("EkipmanTurId")]
        [InverseProperty("ArizaTuru")]
        public virtual Ekipman EkipmanTur { get; set; }
        [ForeignKey("EkipmanTurId")]
        [InverseProperty("ArizaTuru")]
        public virtual EkipmanTur EkipmanTurNavigation { get; set; }
    }
}