// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Ariza
    {
        [Key]
        public int ArizaId { get; set; }
        public int EkipmanId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ArizaBaslangicTarihi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ArizaBitisTarihi { get; set; }
        public int ArizaTuruId { get; set; }
        [StringLength(10)]
        public string ArizaTuruAciklama { get; set; }

        [ForeignKey("EkipmanId")]
        [InverseProperty("Ariza")]
        public virtual Ekipman Ekipman { get; set; }
    }
}