// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Brans
    {
        public Brans()
        {
            Personel = new HashSet<Personel>();
        }

        [Key]
        public int BransId { get; set; }
        [Required]
        [StringLength(10)]
        public string BransAd { get; set; }

        [InverseProperty("Brans")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}