// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class EkipmanTur
    {
        public EkipmanTur()
        {
            ArizaTuru = new HashSet<ArizaTuru>();
            Ekipman = new HashSet<Ekipman>();
        }

        [Key]
        public int EkipmanTurId { get; set; }
        [Required]
        [StringLength(10)]
        public string EkipmanTurAd { get; set; }

        [InverseProperty("EkipmanTurNavigation")]
        public virtual ICollection<ArizaTuru> ArizaTuru { get; set; }
        [InverseProperty("EkipmanTur")]
        public virtual ICollection<Ekipman> Ekipman { get; set; }
    }
}