// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Ekipman
    {
        public Ekipman()
        {
            Ariza = new HashSet<Ariza>();
            ArizaTuru = new HashSet<ArizaTuru>();
        }

        [Key]
        public int EkipmanId { get; set; }
        [Required]
        [StringLength(10)]
        public string EkipmanKod { get; set; }
        public int IstasyonId { get; set; }
        public int SistemId { get; set; }
        public int? EkipmanTurId { get; set; }

        [ForeignKey("EkipmanTurId")]
        [InverseProperty("Ekipman")]
        public virtual EkipmanTur EkipmanTur { get; set; }
        [ForeignKey("IstasyonId")]
        [InverseProperty("Ekipman")]
        public virtual Istasyon Istasyon { get; set; }
        [ForeignKey("SistemId")]
        [InverseProperty("Ekipman")]
        public virtual Sistem Sistem { get; set; }
        [InverseProperty("Ekipman")]
        public virtual ICollection<Ariza> Ariza { get; set; }
        [InverseProperty("EkipmanTur")]
        public virtual ICollection<ArizaTuru> ArizaTuru { get; set; }
    }
}