// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Gorev
    {
        public Gorev()
        {
            Personel = new HashSet<Personel>();
        }

        [Key]
        public int GorevId { get; set; }
        [Required]
        [StringLength(10)]
        public string GorevAd { get; set; }

        [InverseProperty("Gorev")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}