// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Personel
    {
        public Personel()
        {
            Istasyon = new HashSet<Istasyon>();
            Sistem = new HashSet<Sistem>();
        }

        [Key]
        public int PersonelId { get; set; }
        [Required]
        [StringLength(10)]
        public string Ad { get; set; }
        [Required]
        [StringLength(10)]
        public string Soyad { get; set; }
        [Required]
        [StringLength(10)]
        public string TcNo { get; set; }
        public int BransId { get; set; }
        public int GorevId { get; set; }

        [ForeignKey("BransId")]
        [InverseProperty("Personel")]
        public virtual Brans Brans { get; set; }
        [ForeignKey("GorevId")]
        [InverseProperty("Personel")]
        public virtual Gorev Gorev { get; set; }
        [InverseProperty("Personel")]
        public virtual ICollection<Istasyon> Istasyon { get; set; }
        [InverseProperty("Personel")]
        public virtual ICollection<Sistem> Sistem { get; set; }
    }
}