// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MarmarayBakimMVC.Models
{
    public partial class Sistem
    {
        public Sistem()
        {
            Ekipman = new HashSet<Ekipman>();
        }

        [Key]
        public int SistemId { get; set; }
        [Required]
        [StringLength(10)]
        public string SistemAdi { get; set; }
        public int BolgeId { get; set; }
        public int PersonelId { get; set; }

        [ForeignKey("BolgeId")]
        [InverseProperty("Sistem")]
        public virtual Bolge Bolge { get; set; }
        [ForeignKey("PersonelId")]
        [InverseProperty("Sistem")]
        public virtual Personel Personel { get; set; }
        [InverseProperty("Sistem")]
        public virtual ICollection<Ekipman> Ekipman { get; set; }
    }
}